export const FETCH_ALL_TRANSPORTATIONCHECKLISTS_PENDING = "FETCH_ALL_TRANSPORTATIONCHECKLISTS_PENDING";
export const FETCH_ALL_TRANSPORTATIONCHECKLISTS_SUCCESS = "FETCH_ALL_TRANSPORTATIONCHECKLISTS_SUCCESS";
export const FETCH_ALL_TRANSPORTATIONCHECKLISTS_FAILED = "FETCH_ALL_TRANSPORTATIONCHECKLISTS_FAILED";

export const FETCH_ONE_TRANSPORTATIONCHECKLIST_PENDING = "FETCH_ONE_TRANSPORTATIONCHECKLIST_PENDING";
export const FETCH_ONE_TRANSPORTATIONCHECKLIST_SUCCESS = "FETCH_ONE_TRANSPORTATIONCHECKLIST_SUCCESS";
export const FETCH_ONE_TRANSPORTATIONCHECKLIST_FAILED = "FETCH_ONE_TRANSPORTATIONCHECKLIST_FAILED";

export const ADD_TRANSPORTATIONCHECKLIST_PENDING = "ADD_TRANSPORTATIONCHECKLIST_PENDING";
export const ADD_TRANSPORTATIONCHECKLIST_SUCCESS = "ADD_TRANSPORTATIONCHECKLIST_SUCCESS";
export const ADD_TRANSPORTATIONCHECKLIST_FAILED = "ADD_TRANSPORTATIONCHECKLIST_FAILED";

export const UPDATE_TRANSPORTATIONCHECKLIST_PENDING = "UPDATE_TRANSPORTATIONCHECKLIST_PENDING";
export const UPDATE_TRANSPORTATIONCHECKLIST_SUCCESS = "UPDATE_TRANSPORTATIONCHECKLIST_SUCCESS";
export const UPDATE_TRANSPORTATIONCHECKLIST_FAILED = "UPDATE_TRANSPORTATIONCHECKLIST_FAILED";

export const REMOVE_TRANSPORTATIONCHECKLIST_PENDING = "REMOVE_TRANSPORTATIONCHECKLIST_PENDING";
export const REMOVE_TRANSPORTATIONCHECKLIST_SUCCESS = "REMOVE_TRANSPORTATIONCHECKLIST_SUCCESS";
export const REMOVE_TRANSPORTATIONCHECKLIST_FAILED = "REMOVE_TRANSPORTATIONCHECKLIST_FAILED";

export const BASE_URL = "http://localhost:8000/transportationCheckList";
