export const FETCH_ALL_CLAIMS_PENDING = "FETCH_ALL_CLAIMS_PENDING";
export const FETCH_ALL_CLAIMS_SUCCESS = "FETCH_ALL_CLAIMS_SUCCESS";
export const FETCH_ALL_CLAIMS_FAILED = "FETCH_ALL_CLAIMS_FAILED";

export const FETCH_ONE_CLAIM_PENDING = "FETCH_ONE_CLAIM_PENDING";
export const FETCH_ONE_CLAIM_SUCCESS = "FETCH_ONE_CLAIM_SUCCESS";
export const FETCH_ONE_CLAIM_FAILED = "FETCH_ONE_CLAIM_FAILED";

export const ADD_CLAIM_PENDING = "ADD_CLAIM_PENDING";
export const ADD_CLAIM_SUCCESS = "ADD_CLAIM_SUCCESS";
export const ADD_CLAIM_FAILED = "ADD_CLAIM_FAILED";

export const UPDATE_CLAIM_PENDING = "UPDATE_CLAIM_PENDING";
export const UPDATE_CLAIM_SUCCESS = "UPDATE_CLAIM_SUCCESS";
export const UPDATE_CLAIM_FAILED = "UPDATE_CLAIM_FAILED";

export const REMOVE_CLAIM_PENDING = "REMOVE_CLAIM_PENDING";
export const REMOVE_CLAIM_SUCCESS = "REMOVE_CLAIM_SUCCESS";
export const REMOVE_CLAIM_FAILED = "REMOVE_CLAIM_FAILED";

export const BASE_URL = "http://localhost:8080/claims";
