export const FETCH_ALL_CARNOTONPOLICYCKLISTS_PENDING = "FETCH_ALL_CARNOTONPOLICYCKLISTS_PENDING";
export const FETCH_ALL_CARNOTONPOLICYCKLISTS_SUCCESS = "FETCH_ALL_CARNOTONPOLICYCKLISTS_SUCCESS";
export const FETCH_ALL_CARNOTONPOLICYCKLISTS_FAILED = "FETCH_ALL_CARNOTONPOLICYCKLISTS_FAILED";

export const FETCH_ONE_CARNOTONPOLICYCKLIST_PENDING = "FETCH_ONE_CARNOTONPOLICYCKLIST_PENDING";
export const FETCH_ONE_CARNOTONPOLICYCKLIST_SUCCESS = "FETCH_ONE_CARNOTONPOLICYCKLIST_SUCCESS";
export const FETCH_ONE_CARNOTONPOLICYCKLIST_FAILED = "FETCH_ONE_CARNOTONPOLICYCKLIST_FAILED";

export const ADD_CARNOTONPOLICYCKLIST_PENDING = "ADD_CARNOTONPOLICYCKLIST_PENDING";
export const ADD_CARNOTONPOLICYCKLIST_SUCCESS = "ADD_CARNOTONPOLICYCKLIST_SUCCESS";
export const ADD_CARNOTONPOLICYCKLIST_FAILED = "ADD_CARNOTONPOLICYCKLIST_FAILED";

export const UPDATE_CARNOTONPOLICYCKLIST_PENDING = "UPDATE_CARNOTONPOLICYCKLIST_PENDING";
export const UPDATE_CARNOTONPOLICYCKLIST_SUCCESS = "UPDATE_CARNOTONPOLICYCKLIST_SUCCESS";
export const UPDATE_CARNOTONPOLICYCKLIST_FAILED = "UPDATE_CARNOTONPOLICYCKLIST_FAILED";

export const REMOVE_CARNOTONPOLICYCKLIST_PENDING = "REMOVE_CARNOTONPOLICYCKLIST_PENDING";
export const REMOVE_CARNOTONPOLICYCKLIST_SUCCESS = "REMOVE_CARNOTONPOLICYCKLIST_SUCCESS";
export const REMOVE_CARNOTONPOLICYCKLIST_FAILED = "REMOVE_CARNOTONPOLICYCKLIST_FAILED";

export const BASE_URL = "http://localhost:8080/carNotOnPolicyCheckList";
