export const FETCH_ALL_COVERAGECHECKLISTS_PENDING = "FETCH_ALL_COVERAGECHECKLISTS_PENDING";
export const FETCH_ALL_COVERAGECHECKLISTS_SUCCESS = "FETCH_ALL_COVERAGECHECKLISTS_SUCCESS";
export const FETCH_ALL_COVERAGECHECKLISTS_FAILED = "FETCH_ALL_COVERAGECHECKLISTS_FAILED";

export const FETCH_ONE_COVERAGECHECKLIST_PENDING = "FETCH_ONE_COVERAGECHECKLIST_PENDING";
export const FETCH_ONE_COVERAGECHECKLIST_SUCCESS = "FETCH_ONE_COVERAGECHECKLIST_SUCCESS";
export const FETCH_ONE_COVERAGECHECKLIST_FAILED = "FETCH_ONE_COVERAGECHECKLIST_FAILED";

export const ADD_COVERAGECHECKLIST_PENDING = "ADD_COVERAGECHECKLIST_PENDING";
export const ADD_COVERAGECHECKLIST_SUCCESS = "ADD_COVERAGECHECKLIST_SUCCESS";
export const ADD_COVERAGECHECKLIST_FAILED = "ADD_COVERAGECHECKLIST_FAILED";

export const UPDATE_COVERAGECHECKLIST_PENDING = "UPDATE_COVERAGECHECKLIST_PENDING";
export const UPDATE_COVERAGECHECKLIST_SUCCESS = "UPDATE_COVERAGECHECKLIST_SUCCESS";
export const UPDATE_COVERAGECHECKLIST_FAILED = "UPDATE_COVERAGECHECKLIST_FAILED";

export const REMOVE_COVERAGECHECKLIST_PENDING = "REMOVE_COVERAGECHECKLIST_PENDING";
export const REMOVE_COVERAGECHECKLIST_SUCCESS = "REMOVE_COVERAGECHECKLIST_SUCCESS";
export const REMOVE_COVERAGECHECKLIST_FAILED = "REMOVE_COVERAGECHECKLIST_FAILED";

export const BASE_URL = "http://localhost:8080/coverageCheckList";
