export const FETCH_ALL_CARNOTONPOLICYCHECKLISTS_PENDING = "FETCH_ALL_CARNOTONPOLICYCHECKLISTS_PENDING";
export const FETCH_ALL_CARNOTONPOLICYCHECKLISTS_SUCCESS = "FETCH_ALL_CARNOTONPOLICYCHECKLISTS_SUCCESS";
export const FETCH_ALL_CARNOTONPOLICYCHECKLISTS_FAILED = "FETCH_ALL_CARNOTONPOLICYCHECKLISTS_FAILED";

export const FETCH_ONE_CARNOTONPOLICYCHECKLIST_PENDING = "FETCH_ONE_CARNOTONPOLICYCHECKLIST_PENDING";
export const FETCH_ONE_CARNOTONPOLICYCHECKLIST_SUCCESS = "FETCH_ONE_CARNOTONPOLICYCHECKLIST_SUCCESS";
export const FETCH_ONE_CARNOTONPOLICYCHECKLIST_FAILED = "FETCH_ONE_CARNOTONPOLICYCHECKLIST_FAILED";

export const ADD_CARNOTONPOLICYCHECKLIST_PENDING = "ADD_CARNOTONPOLICYCHECKLIST_PENDING";
export const ADD_CARNOTONPOLICYCHECKLIST_SUCCESS = "ADD_CARNOTONPOLICYCHECKLIST_SUCCESS";
export const ADD_CARNOTONPOLICYCHECKLIST_FAILED = "ADD_CARNOTONPOLICYCHECKLIST_FAILED";

export const UPDATE_CARNOTONPOLICYCHECKLIST_PENDING = "UPDATE_CARNOTONPOLICYCHECKLIST_PENDING";
export const UPDATE_CARNOTONPOLICYCHECKLIST_SUCCESS = "UPDATE_CARNOTONPOLICYCHECKLIST_SUCCESS";
export const UPDATE_CARNOTONPOLICYCHECKLIST_FAILED = "UPDATE_CARNOTONPOLICYCHECKLIST_FAILED";

export const REMOVE_CARNOTONPOLICYCHECKLIST_PENDING = "REMOVE_CARNOTONPOLICYCHECKLIST_PENDING";
export const REMOVE_CARNOTONPOLICYCHECKLIST_SUCCESS = "REMOVE_CARNOTONPOLICYCHECKLIST_SUCCESS";
export const REMOVE_CARNOTONPOLICYCHECKLIST_FAILED = "REMOVE_CARNOTONPOLICYCHECKLIST_FAILED";

export const BASE_URL = "http://localhost:8080/carNotOnPolicyCheckList";
